# Generated by Django 4.1.4 on 2023-10-15 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cakevarients',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cakevarient',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customization',
            name='cakevarient',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='cakevarient',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='cakevarient',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='cakevarient',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='CakeCategory',
        ),
        migrations.DeleteModel(
            name='CakeVarients',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Customization',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
