# Generated by Django 4.2.7 on 2023-11-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0006_remove_reviews_cakevarient_reviews_cake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='status',
            field=models.CharField(choices=[('in-cart', 'in-cart'), ('order-placed', 'order-placed'), ('deliverd', 'delivered'), ('cancelled', 'cancelled')], default='in-cart', max_length=200),
        ),
    ]
